<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Evands.Pellucid.CwsConsole</RootNamespace>
    <AssemblyName>Evands.Pellucid.CwsConsole</AssemblyName>
    <AssemblyVersion>1.0.0.200</AssemblyVersion>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Test'">
    <InternalsVisibleTo Include="Evands.Pellucid.Tests" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' != 'Test'">
    <PackageReference Include="Crestron.SimplSharp.SDK.Library" Version="2.21.226" GeneratePathProperty="true" ExcludeAssets="all" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' != 'Test'">
    <Reference Include="SimplSharpHelperInterface">
      <HintPath>$(PkgCrestron_SimplSharp_SDK_Library)\lib\SimplSharpHelperInterface.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Test'">
    <ProjectReference Include="..\Evands.Pellucid.Fakes\Evands.Pellucid.Fakes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Evands.Pellucid\Evands.Pellucid.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\CwsConsoleTemplate.html" />
    <EmbeddedResource Include="Resources\default.css" />
    <EmbeddedResource Include="Resources\greenScreen.css" />
  </ItemGroup>
</Project>
