<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Evands.Pellucid</RootNamespace>
    <AssemblyName>Evands.Pellucid.Tests</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Configurations>Test</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Evands.Pellucid\Evands.Pellucid.csproj" />
    <ProjectReference Include="..\Evands.Pellucid.Crestron\Evands.Pellucid.Crestron.csproj" />
    <ProjectReference Include="..\Evands.Pellucid.Fakes\Evands.Pellucid.Fakes.csproj" />
  </ItemGroup>
</Project>
