<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Evands.Pellucid</RootNamespace>
    <AssemblyName>Evands.Pellucid</AssemblyName>
    <AssemblyVersion>1.5.2.1000</AssemblyVersion>
    <Version>1.5.2</Version>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Test'">
    <InternalsVisibleTo Include="Evands.Pellucid.Tests" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' != 'Test'">
    <PackageReference Include="Crestron.SimplSharp.SDK.Library" Version="2.21.226" GeneratePathProperty="true" ExcludeAssets="all" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' != 'Test'">
    <Reference Include="SimplSharpHelperInterface">
      <HintPath>$(PkgCrestron_SimplSharp_SDK_Library)\lib\SimplSharpHelperInterface.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Test'">
    <ProjectReference Include="..\Evands.Pellucid.Fakes\Evands.Pellucid.Fakes.csproj" />
  </ItemGroup>
</Project>
