<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Company>Elegant Video and Soundworks</Company>
    <Copyright>Copyright © Christopher McNeely $([System.DateTime]::Now.Year)</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Test'">
    <DefineConstants>$(DefineConstants);TEST</DefineConstants>
  </PropertyGroup>
</Project>
