<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Evands.Pellucid.ProDemo</RootNamespace>
    <AssemblyName>Evands.Pellucid.ProDemo</AssemblyName>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Version>1.0.0</Version>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Crestron.SimplSharp.SDK.Program" Version="2.21.226" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Evands.Pellucid\Evands.Pellucid.csproj" />
    <ProjectReference Include="..\Evands.Pellucid.Crestron\Evands.Pellucid.Crestron.csproj" />
  </ItemGroup>
</Project>
