name: CreateRelease

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/Evands.Pellucid.slnx --property:Configuration=Release

      - name: Build
        run: dotnet build src/Evands.Pellucid.slnx --configuration Release --no-restore

      - name: Pack
        run: dotnet pack src/Evands.Pellucid/Evands.Pellucid.csproj --configuration Release --no-build --output ./packaging/.releases

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-output
          path: |
            ./packaging/.releases/*.nupkg