name: RunTests

on:
  push:
    branches: [ main, dev-* ]
    paths-ignore:
      - 'packaging/*'
      - '.github/workflows/CreateRelease.yml'
      - 'scripts/*'
      - '*.md'
      - 'LICENSE'
      - 'Settings.StyleCop'
      - '.gitignore'
      - '*.png'
  pull_request:
    branches: [ main, dev-* ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/Evands.Pellucid.slnx --property:Configuration=Test

      - name: Build
        run: dotnet build src/Evands.Pellucid.Tests/Evands.Pellucid.Tests.csproj --configuration Test --no-restore

      - name: Test
        run: dotnet run --project src/Evands.Pellucid.Tests/Evands.Pellucid.Tests.csproj --configuration Test --no-build
