# This is a basic workflow to help you get started with Actions

name: RunTests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
    branches: [ main ]
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: scripts/buildProject.ps1 -Mode Test
      - uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: |
            src/Evands.Pellucid/bin/Test/Evands.Pellucid.dll
            src/Evands.Pellucid.Pro/bin/Test/Evands.Pellucid.Pro.dll
            src/Evands.Pellucid.Tests/bin/Test/Evands.Pellucid.Tests.dll
      
  
  testCoverageReport:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: test-output
      - run: testing/generateReport.ps1
